FROM microsoft/dotnet:latest
ENV TEST_1 "foo"
ENV TEST_2 "foo"
ENV TEST_3 "foo"
ENV TEST_4 "foo"
ENV TEST_5 "foo"
ENV TEST_6 "foo"
ENV TEST_7 "foo"
ENV TEST_8 "foo"
ENV TEST_9 "foo"
ENV TEST_10 "foo"
ENV TEST_11 "bar"
